Repository Vizzuality/tnc-blue-carbon-cost-tool, pull requests merged in 2024-11, with the labels that each got.

#76 implements UI kit - first iteration
  client/package.json
  client/src/app/(projects)/page.tsx
  client/src/app/(projects)/store.ts
  client/src/app/fonts/GeistMonoVF.woff
  client/src/app/fonts/GeistVF.woff
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/components/map/constants.ts
  client/src/components/map/index.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/pagination.tsx
  client/src/components/ui/popover.tsx
  client/src/components/ui/resizable.tsx
  client/src/components/ui/scroll-area.tsx
  client/src/components/ui/search.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/sidebar.tsx
  client/src/components/ui/table.tsx
  client/src/components/ui/tabs.tsx
  client/src/components/ui/tooltip.tsx
  client/src/containers/nav/index.tsx
  client/src/containers/projects/filters/index.tsx
  client/src/containers/projects/header/index.tsx
  client/src/containers/projects/header/parameters/index.tsx
  client/src/containers/projects/map/controls/legend/index.tsx
  client/src/containers/projects/map/controls/zoom/index.tsx
  client/src/containers/projects/map/index.tsx
  client/src/containers/projects/map/layers/projects/index.tsx
  client/src/containers/projects/map/layers/projects/utils.ts
  client/src/containers/projects/map/legend/index.tsx
  client/src/containers/projects/map/legend/types/matrix.tsx
  client/src/containers/projects/table/index.tsx
  client/src/containers/projects/table/pagination/index.tsx
  client/src/containers/projects/table/toolbar/index.tsx
  client/src/containers/projects/table/toolbar/info-download/index.tsx
  client/src/containers/projects/table/toolbar/search/index.tsx
  client/src/containers/projects/table/view/key-costs/index.tsx
  client/src/containers/projects/table/view/overview/index.tsx
  client/tailwind.config.ts
  pnpm-lock.yaml
Labels: front-end

#87 fixes wrong filter keys for costs and abatement
  client/src/containers/projects/filters/index.tsx
Labels: front-end

#85 [TBCCT-124] adds popup to map
  client/src/app/(overview)/store.ts
  client/src/app/globals.css
  client/src/components/map/index.tsx
  client/src/components/map/popup/index.tsx
  client/src/components/ui/badge.tsx
  client/src/containers/projects/map/index.tsx
  client/src/containers/projects/map/layers/projects/index.tsx
  client/src/containers/projects/map/popup/index.tsx
  client/src/lib/format.tsx
Labels: front-end

#91 adds tooltip to thumb slider
  client/src/components/ui/slider.tsx
  client/src/containers/projects/filters/index.tsx
  client/src/lib/format.tsx
Labels: front-end

#92 [N/A] renames projects container to overview
  client/src/app/(overview)/page.tsx
  client/src/app/(overview)/url-store.ts
  client/src/containers/overview/filters/constants.ts
  client/src/containers/overview/filters/index.tsx
  client/src/containers/overview/header/index.tsx
  client/src/containers/overview/header/parameters/index.tsx
  client/src/containers/overview/map/controls/index.tsx
  client/src/containers/overview/map/controls/zoom/index.tsx
  client/src/containers/overview/map/index.tsx
  client/src/containers/overview/map/layers/projects/index.tsx
  client/src/containers/overview/map/layers/projects/utils.ts
  client/src/containers/overview/map/legend/types/matrix.tsx
  client/src/containers/overview/map/popup/index.tsx
  client/src/containers/overview/table/index.tsx
  client/src/containers/overview/table/pagination/index.tsx
  client/src/containers/overview/table/toolbar/index.tsx
  client/src/containers/overview/table/toolbar/search/index.tsx
  client/src/containers/overview/table/toolbar/table-selector/index.tsx
  client/src/containers/overview/table/utils.ts
  client/src/containers/overview/table/view/key-costs/columns.tsx
  client/src/containers/overview/table/view/key-costs/index.tsx
  client/src/containers/overview/table/view/overview/columns.tsx
  client/src/containers/overview/table/view/overview/index.tsx
  client/src/containers/overview/table/view/scorecard-prioritization/columns.tsx
  client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
  client/src/lib/query-keys.ts
Labels: front-end

#93 Add overview page calculations
  data/.gitignore
  data/notebooks/High_level_overview.ipynb
  data/src/bcc_model/blue_carbon_project.py
  data/src/bcc_model/cost_calculator.py
  data/src/bcc_model/revenue_profit_calculator.py
  data/src/bcc_model/sequestration_credits_calculator.py
  data/src/bcc_model/utils.py
Labels: data

#100 [N/A] fixes sync of cost value with query params
  client/src/containers/overview/filters/index.tsx
  client/src/containers/overview/header/parameters/index.tsx
Labels: front-end

#99 Changed cookie name
  client/src/app/auth/api/[...nextauth]/config.ts
Labels: front-end

#101 [N/A] pnpm@9.13.2
  package.json
Labels: dependencies

#118 Include missing columns in 'projects' tab in data_ingestion_WIP excel file
  data/excel/data_ingestion_WIP.xlsm
  data/notebooks/High_level_overview.ipynb
Labels: data
