Repository Vizzuality/tnc-blue-carbon-cost-tool, pull requests merged in 2025-05, with the labels that each got.

#412 fix(client): change color score-card value
  client/src/containers/overview/project-details/score-card-rating/index.tsx
  client/src/containers/projects/form/number-form-item.tsx
Labels: front-end

#416 fix(backoffice): overflow sources items
  backoffice/components/molecules/many-2-many-sources.tsx
Labels: backoffice

#420 [TBCCT-385] implements sensitivity analysis
  client/src/components/ui/bar-chart/single-stacked-bar-chart/index.tsx
  client/src/containers/overview/table/utils.tsx
  client/src/containers/projects/custom-project/cost-details/index.tsx
  client/src/containers/projects/custom-project/cost-details/table/columns.tsx
  client/src/containers/projects/custom-project/cost-details/table/index.tsx
  client/src/containers/projects/custom-project/cost-details/table/sensitivity-analysis/index.tsx
  client/src/hooks/use-custom-project-output.ts
  shared/dtos/custom-projects/custom-project-output.dto.ts
Labels: front-end

#423 feat(client): get plantingSuccessRate from api
  client/src/containers/projects/form/setup/activity/index.tsx
  e2e/tests/custom-projects/edit-custom-project.spec.ts
  shared/schemas/custom-projects/custom-project-form.constants.ts
Labels: front-end

#430 [TBCCT-383] fixes undefined lossRate in restoration projects
  client/src/containers/projects/form/setup/activity/index.tsx
  client/src/containers/projects/form/setup/conservation-project-details/index.tsx
  e2e/lib/utils.ts
  e2e/tests/custom-projects/edit-custom-project.spec.ts
Labels: front-end

#435 [TBCCT-407] adds scroll in dialogs by default
  client/src/components/ui/info-button.tsx
  client/src/containers/projects/custom-project/cost-details/index.tsx
Labels: front-end

#433 [TBCCT-410] replaces "Community benefit sharing fund" with "Landowner/community benefit share"
  api/test/integration/custom-projects/custom-projects-save.spec.ts
  client/src/containers/methodology/table/data.tsx
  client/src/containers/overview/project-details/utils.ts
  client/src/containers/overview/table/toolbar/index.tsx
  client/src/hooks/use-custom-project-output.ts
  client/tests/projects/form/constants.ts
Labels: front-end

#436 [TBCCT-418] moves project summary to sheet to improve page responsiveness
  client/src/components/ui/graph.tsx
  client/src/components/ui/sheet.tsx
  client/src/containers/projects/custom-project/index.tsx
  client/src/containers/projects/custom-project/summary/index.tsx
  e2e/tests/custom-projects/edit-custom-project.spec.ts
Labels: front-end

#443 [TBCCT-424] cost details: moves implementation labor cost to capital expenditure
  client/src/containers/projects/custom-project/cost-details/table/utils.ts
Labels: front-end

#446 [TBCCT-411] methodology scroll spy: reduces negative bottom margin
  client/src/containers/methodology/index.tsx
Labels: front-end

#447 [N/A] @types/node@22.15.21
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: front-end, back-end

#444 [TBCCT-408] updates tooltips content
  client/src/components/ui/list.tsx
  client/src/constants/tooltip.tsx
  client/src/containers/overview/filters/index.tsx
  client/src/containers/overview/header/parameters/index.tsx
  client/src/containers/overview/table/toolbar/index.tsx
  client/src/containers/projects/custom-project/header/parameters/index.tsx
  client/src/containers/projects/form/cost-inputs-overrides/index.tsx
  client/src/containers/projects/form/restoration-plan/index.tsx
  client/src/containers/projects/form/setup/index.tsx
  client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
  shared/schemas/assumptions/assumptions.enums.ts
Labels: front-end

#462 [N/A] fixes an issue where inner button will trigger the accordion on click
  client/src/components/ui/info-button.tsx
  client/src/containers/projects/form/cost-inputs-overrides/index.tsx
  client/src/containers/projects/form/restoration-plan/index.tsx
Labels: front-end
